- hosts: d7_shelepen
  gather_facts: yes
  sudo: true
  vars_files:
  - variables.yml
  tasks:
  - include: sysutils.yml
  - include: project.yml
  - include: develop.yml
  handlers:
  - include: handlers.yml

