<?php
/**
 * @file The main module file.
 */

define ("CM_FACEBOOK_APP_ID", 1586065378339731);

// It loads helpers.
module_load_include('inc', 'cm');

/**
 * Implements hook_menu.
 */
function cm_menu() {
  $items['cm/test_form'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cm_test_form'),
    'access callback' => TRUE,
  );

  $items['s/%'] = array(
    'page callback' => 'cm_shorten_callback',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Implements hook_field_formatter_info().
 */
function cm_field_formatter_info() {
  return array(
    'cm_single_image_formatter' => array (
      'label' => t('Single Image'),
      'field types' => array ('image'),
      'settings'  => array (
        'image_style' => 'large',
        'position' => 0
      ),
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function cm_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $summary = t('imageStyle=@imageStyle, position=@position', array(
    '@imageStyle' => $settings['image_style'],
    '@position' => $settings['position']
  ));

  return $summary;
}

/**
 * Implements hook_field_formatter_settings_form.
 */
function cm_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];


  $style_options = [];
  foreach(image_styles() as $key => $style) {
    $style_options[$key] = $style['label'];
  }
  $element = [];
  $element['image_style'] = [
    '#title' => t('Image style'),
    '#type' => 'select',
    '#options' => $style_options,
    '#default_value' => $settings['image_style'] ? $settings['image_style'] : 'large',
  ];
  $element['position'] = [
    '#title' => t('Position'),
    '#type' => 'textfield',
    '#default_value' => $settings['position'] ? $settings['position'] : 0,
  ];

  return $element;
}

/**
 * Implements hook_field_formatter_view().
 */
function cm_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $settings = $display['settings']; // get the settings

  return  [
    '#theme' => 'image_formatter',
    '#item' => [
      'uri' => $items[$settings['position']]['uri'],
    ],
    '#image_style' => $settings['image_style'],
  ];
}

/**
 * Implements menu callback for - s/% .
 */
function cm_shorten_callback($pid) {
  $alias = db_select('url_alias', 'u')
    ->fields('u', ['pid', 'source', 'language'])
    ->condition('pid', $pid)
    ->execute()
    ->fetchAssoc();

  $redirect_to = $alias['language'] . '/' .$alias['source'];
  $languages = language_list();
  $language = $languages[$alias['language']];
  drupal_goto($alias['source'], [
    'language' => $language
  ]);
}

/**
* Implements hook_entity_info_alter().
*/
function cm_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['popup'] = array(
    'label' => t('Popup'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_form_alter.
 */
function cm_form_alter(&$form, &$form_state, $form_id) {
}

/**
 * Processes the page cm/test.
 */
function cm_test_form() {
  $form = [];

  $form['cm_imce'] = array (
    '#type' => 'cm_imce',
    '#attributes' => array ('id' => 'urlField'),
    '#title' => 'fadsf'
  );

  $form['cm_imce_1'] = array (
    '#type' => 'cm_imce',
    '#attributes' => array ('id' => 'urlField'),
    '#title' => 'Title 1'
  );

  return $form;
}

/**
 * Implements hook_elements.
 */
function cm_element_info() {
  return array (
    'cm_imce' => array(
      '#input' => TRUE,
      '#process' => array('cm_imce_element_process'),
      '#example_attribute' => 'Something extra',
      '#theme_wrappers' => array('form_element'),
    ),
  );
}

/**
 * Processes the element cm_imce.
 */
function cm_imce_element_process($element) {
  $id = $element['#id'] . '-' . time();

  return array (
    '#type' => 'container',
    '#weight' => $element['#weight'],
    '#attributes' => array (
      'class' => array ('cm_imce_element'),
    ),
    '#attached' => array (
      'js' => array (
        drupal_get_path('module', 'cm') . '/js/imce_element.js'
      ),
    ),
    'label' => array (
      '#markup' => '<label>' . check_plain($element['#title']) . '</lable>',
    ),
    'container' => array (
      '#type' => 'container',
      '#attributes' => array (
        'class' => array ('container-inline'),
      ),
      $element['#name'] => array (
        '#type' => 'textfield',
        '#id' => $id,
        '#default_value' => $element['#default_value'],
      ),
      'browse' => array (
        '#type' => 'button',
        '#value' => t('Browse'),
        '#attributes' => array (
          'onclick' => 'return (false);',
          'data-title' => $element['#imce_title'],
          'data-id' => $id,
        ),
      ),
    ),
  );
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function cm_ctools_plugin_directory($module, $plugin) {
  if (in_array($module, array('ctools', 'panels')) && !empty($plugin)) {
    return 'plugins/' . $plugin;
  }
}
